//! `cargo xtask bundle [--release|--debug] [--open] [--release-id] [--sign IDENTITY|--adhoc]
//! [--reset-permissions]`: a local macOS `FilmCraft Dev.app` (`FilmCraft.app` with the release
//! bundle id under `--release-id`).
//!
//! Builds the `filmcraft` binary and assembles `<target>/<profile>/FilmCraft Dev.app` with its own
//! Info.plist (camera / microphone usage descriptions, document types), the icon and a signature,
//! so macOS attributes the camera, microphone and Screen Recording permissions to FilmCraft
//! instead of the terminal that started it. It copies the binary and the icon only: everything
//! else is embedded. Release packaging (universal binary, Developer ID, notarisation, DMG) is
//! `packaging/macos/package.sh`. On other hosts it does nothing.
//!
//! The signature decides whether those permissions last ([`Signing`]): signed with the local
//! identity of `cargo xtask dev-identity` (`identity.rs`; used whenever it exists) or with an
//! identity of the user's keychains (`--sign`, `FILMCRAFT_SIGN_IDENTITY`), every build is the same
//! app to macOS; signed ad hoc (no identity, or `--adhoc`) every build is a new one.
//! `--reset-permissions` drops the app's permission records (`tccutil reset All <bundle id>`),
//! needed once after the way it is signed changed.

use std::path::{Path, PathBuf};
use std::process::Command;

use crate::identity::{self, Identity};

/// The bundle identifier, the same as the release bundle (`packaging/macos/Info.plist.in`) and the
/// Linux app id (`packaging/linux/ai.storyteller.filmcraft.desktop`).
pub const BUNDLE_ID: &str = "ai.storyteller.filmcraft";
/// The local build's bundle id and name. A local bundle must not share the release id: Launch
/// Services resolves a bundle id to the registered copy, so `open` on a local `FilmCraft.app` can
/// start an installed release instead (it did, on the owner's Mac, with FilmCraft 0.2.1 in
/// /Applications).
pub const DEV_BUNDLE_ID: &str = "ai.storyteller.filmcraft.dev";
pub const DEV_NAME: &str = "FilmCraft Dev";

/// ScreenCaptureKit (linked by `crates/platform/src/capture/screen.rs`) needs macOS 12.3; its
/// macOS 13 API (`capturesAudio`) is checked at run time.
pub const MIN_MACOS: &str = "12.3";

pub const CAMERA_USAGE: &str = "FilmCraft records your camera when you press Record.";
pub const MICROPHONE_USAGE: &str = "FilmCraft records your microphone for voice-over and recordings.";

fn esc(s: &str) -> String {
    s.replace('&', "&amp;").replace('<', "&lt;").replace('>', "&gt;")
}

/// `CFBundleVersion` / `CFBundleShortVersionString` must be numeric: `0.4.0-rc.1` → `0.4.0`.
pub fn short_version(version: &str) -> &str {
    version.split_once('-').map_or(version, |(core, _)| core)
}

/// The bundle's Info.plist for the workspace `version`, bundle `id` and display `name`.
pub fn info_plist(version: &str, id: &str, name: &str) -> String {
    let short = esc(short_version(version));
    let full = esc(version);
    let id = esc(id);
    let name = esc(name);
    let camera = esc(CAMERA_USAGE);
    let mic = esc(MICROPHONE_USAGE);
    format!(
        r#"<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<!-- Generated by `cargo xtask bundle` (xtask/src/bundle.rs). -->
<plist version="1.0">
<dict>
  <key>CFBundleDevelopmentRegion</key>
  <string>en</string>
  <key>CFBundleIdentifier</key>
  <string>{id}</string>
  <key>CFBundleName</key>
  <string>{name}</string>
  <key>CFBundleDisplayName</key>
  <string>{name}</string>
  <key>CFBundleExecutable</key>
  <string>filmcraft</string>
  <key>CFBundleIconFile</key>
  <string>filmcraft</string>
  <key>CFBundleInfoDictionaryVersion</key>
  <string>6.0</string>
  <key>CFBundlePackageType</key>
  <string>APPL</string>
  <key>CFBundleSignature</key>
  <string>????</string>
  <key>CFBundleShortVersionString</key>
  <string>{short}</string>
  <key>CFBundleVersion</key>
  <string>{short}</string>
  <key>FilmCraftVersion</key>
  <string>{full}</string>
  <key>LSMinimumSystemVersion</key>
  <string>{MIN_MACOS}</string>
  <key>LSApplicationCategoryType</key>
  <string>public.app-category.video</string>
  <key>NSHighResolutionCapable</key>
  <true/>
  <key>NSSupportsAutomaticGraphicsSwitching</key>
  <true/>
  <key>NSHumanReadableCopyright</key>
  <string>Copyright © the FilmCraft authors. MIT OR Apache-2.0.</string>
  <key>NSCameraUsageDescription</key>
  <string>{camera}</string>
  <key>NSMicrophoneUsageDescription</key>
  <string>{mic}</string>
  <key>UTExportedTypeDeclarations</key>
  <array>
    <dict>
      <key>UTTypeIdentifier</key>
      <string>{id}.project</string>
      <key>UTTypeDescription</key>
      <string>FilmCraft Project</string>
      <key>UTTypeConformsTo</key>
      <array>
        <string>public.data</string>
        <string>public.json</string>
      </array>
      <key>UTTypeIconFile</key>
      <string>filmcraft</string>
      <key>UTTypeTagSpecification</key>
      <dict>
        <key>public.filename-extension</key>
        <array><string>fcproj</string></array>
        <key>public.mime-type</key>
        <array><string>application/x-filmcraft</string></array>
      </dict>
    </dict>
  </array>
  <key>CFBundleDocumentTypes</key>
  <array>
    <dict>
      <key>CFBundleTypeName</key>
      <string>FilmCraft Project</string>
      <key>CFBundleTypeRole</key>
      <string>Editor</string>
      <key>LSHandlerRank</key>
      <string>Owner</string>
      <key>CFBundleTypeIconFile</key>
      <string>filmcraft</string>
      <key>LSItemContentTypes</key>
      <array><string>{id}.project</string></array>
      <key>CFBundleTypeExtensions</key>
      <array><string>fcproj</string></array>
    </dict>
    <dict>
      <key>CFBundleTypeName</key>
      <string>Media</string>
      <key>CFBundleTypeRole</key>
      <string>Viewer</string>
      <key>LSHandlerRank</key>
      <string>Alternate</string>
      <key>LSItemContentTypes</key>
      <array>
        <string>public.movie</string>
        <string>public.audio</string>
        <string>public.image</string>
      </array>
    </dict>
  </array>
</dict>
</plist>
"#
    )
}

/// `CARGO_TARGET_DIR`, else `<root>/target`.
fn target_dir(root: &Path) -> PathBuf {
    match std::env::var_os("CARGO_TARGET_DIR").map(PathBuf::from) {
        Some(d) if d.is_absolute() => d,
        Some(d) => root.join(d),
        None => root.join("target"),
    }
}

fn dir_size(p: &Path) -> u64 {
    let Ok(md) = std::fs::symlink_metadata(p) else { return 0 };
    if !md.is_dir() {
        return md.len();
    }
    std::fs::read_dir(p).into_iter().flatten().flatten().map(|e| dir_size(&e.path())).sum()
}

fn run(cmd: &mut Command) -> Result<(), String> {
    eprintln!("$ {cmd:?}");
    let st = cmd.status().map_err(|e| format!("{cmd:?}: {e}"))?;
    if st.success() { Ok(()) } else { Err(format!("failed: {cmd:?}")) }
}

pub const USAGE: &str = "cargo xtask bundle [--release|--debug] [--open] [--release-id] [--sign IDENTITY|--adhoc] [--reset-permissions]";

/// How the bundle is signed.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum Signing {
    /// `codesign --sign -`: a new code identity every build, so macOS asks for the permissions
    /// again (and Screen Recording silently stops working) after each one.
    AdHoc,
    /// An identity of the user's own keychains (`--sign`, `FILMCRAFT_SIGN_IDENTITY`): a name or
    /// SHA-1 as `security find-identity -p codesigning` lists it.
    Named(String),
    /// The local identity `cargo xtask dev-identity` made, in its own keychain.
    Dev(Identity),
}

/// What signs the bundle: `--adhoc` / `--sign` first, then `FILMCRAFT_SIGN_IDENTITY` (`-` = ad
/// hoc), then the local dev identity when there is one, else ad hoc.
pub fn signing_for(flag: Option<Signing>, env: Option<&str>, dev: Option<Identity>) -> Signing {
    if let Some(s) = flag {
        return s;
    }
    match env.map(str::trim).filter(|e| !e.is_empty()) {
        Some("-") => Signing::AdHoc,
        Some(e) => Signing::Named(e.to_string()),
        None => dev.map_or(Signing::AdHoc, Signing::Dev),
    }
}

/// What `run_bundle` was asked for.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Options {
    pub release: bool,
    pub open: bool,
    pub release_id: bool,
    pub sign: Option<Signing>,
    pub reset_permissions: bool,
}

pub fn parse_args(args: &[&str]) -> Result<Options, String> {
    let mut o = Options { release: true, open: false, release_id: false, sign: None, reset_permissions: false };
    let mut it = args.iter();
    while let Some(a) = it.next() {
        match *a {
            "--release" => o.release = true,
            "--debug" => o.release = false,
            "--open" => o.open = true,
            "--release-id" => o.release_id = true,
            "--adhoc" => o.sign = Some(Signing::AdHoc),
            "--sign" => match it.next().map(|v| v.trim()).filter(|v| !v.is_empty() && !v.starts_with("--")) {
                Some("-") => o.sign = Some(Signing::AdHoc),
                Some(v) => o.sign = Some(Signing::Named(v.to_string())),
                None => return Err("bundle: --sign needs an identity, a name or SHA-1 from `security find-identity -p codesigning`".into()),
            },
            "--reset-permissions" => o.reset_permissions = true,
            _ => return Err(format!("bundle: unknown argument `{a}` (usage: {USAGE})")),
        }
    }
    Ok(o)
}

/// Sign `app` and return its designated requirement (what macOS ties the app's permissions to).
fn sign(app: &Path, signing: &Signing) -> Result<String, String> {
    let mut cmd = Command::new("codesign");
    cmd.args(["--force", "--deep", "--sign"]);
    match signing {
        Signing::AdHoc => {
            cmd.arg("-");
        }
        Signing::Named(n) => {
            cmd.arg(n);
        }
        Signing::Dev(id) => {
            // a locked keychain would make codesign wait on a password window
            identity::unlock(&identity::dir()?, id)?;
            cmd.arg(&id.sha1).arg("--keychain").arg(&id.keychain);
        }
    }
    run(cmd.arg(app))?;
    run(Command::new("codesign").args(["--verify", "--strict"]).arg(app))?;
    let out = Command::new("codesign").args(["-d", "-r-"]).arg(app).output().map_err(|e| format!("codesign: {e}"))?;
    let text = String::from_utf8_lossy(&out.stdout);
    Ok(text.lines().find_map(|l| l.strip_prefix("designated => ")).unwrap_or("").to_string())
}

pub fn run_bundle(root: &Path, args: &[&str]) -> Result<(), String> {
    let Options { release, open, release_id, sign: sign_flag, reset_permissions } = parse_args(args)?;
    let (id, name) = if release_id { (BUNDLE_ID, "FilmCraft") } else { (DEV_BUNDLE_ID, DEV_NAME) };
    if !cfg!(target_os = "macos") {
        println!("bundle: a macOS app bundle; nothing to do on this host");
        return Ok(());
    }
    let manifest = root.join("Cargo.toml");
    let version = crate::version::read(&std::fs::read_to_string(&manifest).map_err(|e| format!("{}: {e}", manifest.display()))?)?;

    let mut build = Command::new(env!("CARGO"));
    build.current_dir(root).args(["build", "-p", "filmcraft", "--bin", "filmcraft"]);
    if release {
        build.arg("--release");
    }
    run(&mut build)?;

    let profile = if release { "release" } else { "debug" };
    let out = target_dir(root).join(profile);
    let bin = out.join("filmcraft");
    let app = out.join(format!("{name}.app"));
    if app.exists() {
        std::fs::remove_dir_all(&app).map_err(|e| format!("{}: {e}", app.display()))?;
    }
    let contents = app.join("Contents");
    let macos = contents.join("MacOS");
    let resources = contents.join("Resources");
    for d in [&macos, &resources] {
        std::fs::create_dir_all(d).map_err(|e| format!("{}: {e}", d.display()))?;
    }
    let copy = |from: &Path, to: &Path| std::fs::copy(from, to).map(|_| ()).map_err(|e| format!("copy {} → {}: {e}", from.display(), to.display()));
    copy(&bin, &macos.join("filmcraft"))?;
    copy(&root.join("assets/app-icon/filmcraft.icns"), &resources.join("filmcraft.icns"))?;
    let write = |p: PathBuf, data: &[u8]| std::fs::write(&p, data).map_err(|e| format!("{}: {e}", p.display()));
    write(contents.join("Info.plist"), info_plist(&version, id, name).as_bytes())?;
    write(contents.join("PkgInfo"), b"APPL????")?;

    run(Command::new("plutil").arg("-lint").arg(contents.join("Info.plist")))?;
    let env = std::env::var("FILMCRAFT_SIGN_IDENTITY").ok();
    let dev = identity::dir().ok().and_then(|d| identity::find(&d));
    let signing = signing_for(sign_flag, env.as_deref(), dev);
    let requirement = sign(&app, &signing)?;
    println!("bundle: {} ({name} {version}, {id}, {profile}, {:.1} MB)", app.display(), dir_size(&app) as f64 / 1e6);
    match &signing {
        Signing::AdHoc => println!(
            "bundle: signed ad hoc: macOS treats every rebuild as a new app (Camera and Microphone are asked again, Screen Recording stops working until its entry is removed). `cargo xtask dev-identity` once makes the permissions last."
        ),
        Signing::Named(n) => println!("bundle: signed with \"{n}\""),
        Signing::Dev(_) => println!("bundle: signed with \"{}\": the permissions macOS gives this app last across rebuilds", identity::NAME),
    }
    if !requirement.is_empty() {
        println!("bundle: requirement: {requirement}");
    }
    if reset_permissions {
        // the records of builds signed another way no longer match this one; macOS asks again
        run(Command::new("tccutil").args(["reset", "All", id]))?;
        println!(
            "bundle: the privacy permissions of {id} are reset: allow Camera and Microphone when asked, and turn {name} on once under System Settings ▸ Privacy & Security ▸ Screen & System Audio Recording"
        );
    }
    if open {
        run(Command::new("open").arg(&app))?;
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn value_of(plist: &str, key: &str) -> Option<String> {
        let tag = format!("<key>{key}</key>");
        let rest = &plist[plist.find(&tag)? + tag.len()..];
        let rest = rest.trim_start();
        if rest.starts_with("<true/>") {
            return Some("true".into());
        }
        let rest = rest.strip_prefix("<string>")?;
        Some(rest[..rest.find("</string>")?].to_string())
    }

    #[test]
    fn info_plist_has_the_keys_and_the_workspace_version() {
        let manifest = std::fs::read_to_string(Path::new(env!("CARGO_MANIFEST_DIR")).join("../Cargo.toml")).unwrap();
        let version = crate::version::read(&manifest).unwrap();
        let p = info_plist(&version, DEV_BUNDLE_ID, DEV_NAME);
        let short = short_version(&version).to_string();
        let r = info_plist(&version, BUNDLE_ID, "FilmCraft");
        assert_eq!(value_of(&r, "CFBundleIdentifier").as_deref(), Some(BUNDLE_ID));
        assert_eq!(value_of(&r, "CFBundleName").as_deref(), Some("FilmCraft"));
        assert!(r.contains(&format!("<string>{BUNDLE_ID}.project</string>")));
        assert_ne!(DEV_BUNDLE_ID, BUNDLE_ID, "a local bundle never takes the release id");
        for (k, v) in [
            ("CFBundleIdentifier", DEV_BUNDLE_ID),
            ("CFBundleName", DEV_NAME),
            ("CFBundleDisplayName", DEV_NAME),
            ("CFBundleExecutable", "filmcraft"),
            ("CFBundleIconFile", "filmcraft"),
            ("CFBundlePackageType", "APPL"),
            ("CFBundleVersion", short.as_str()),
            ("CFBundleShortVersionString", short.as_str()),
            ("FilmCraftVersion", version.as_str()),
            ("LSMinimumSystemVersion", MIN_MACOS),
            ("LSApplicationCategoryType", "public.app-category.video"),
            ("NSHighResolutionCapable", "true"),
            ("NSCameraUsageDescription", CAMERA_USAGE),
            ("NSMicrophoneUsageDescription", MICROPHONE_USAGE),
        ] {
            assert_eq!(value_of(&p, k).as_deref(), Some(v), "{k}");
        }
        for s in [
            "<key>CFBundleDocumentTypes</key>",
            "<string>fcproj</string>",
            "<string>Owner</string>",
            "<string>Editor</string>",
            "<string>public.movie</string>",
            "<string>public.audio</string>",
            "<string>public.image</string>",
            "<string>Alternate</string>",
        ] {
            assert!(p.contains(s), "missing {s}");
        }
        assert!(!p.contains("NSScreenCaptureUsageDescription") && !p.contains("NSAppleEventsUsageDescription"));
        assert_eq!(p.matches("<dict>").count(), p.matches("</dict>").count());
        assert_eq!(p.matches("<array>").count(), p.matches("</array>").count());
    }

    #[test]
    fn arguments_and_the_signing_order() {
        let o = parse_args(&[]).unwrap();
        assert_eq!(o, Options { release: true, open: false, release_id: false, sign: None, reset_permissions: false });
        let o = parse_args(&["--debug", "--open", "--release-id", "--reset-permissions", "--sign", "Apple Development: A (B)"]).unwrap();
        assert!(!o.release && o.open && o.release_id && o.reset_permissions);
        assert_eq!(o.sign, Some(Signing::Named("Apple Development: A (B)".into())));
        assert_eq!(parse_args(&["--adhoc"]).unwrap().sign, Some(Signing::AdHoc));
        assert_eq!(parse_args(&["--sign", "-"]).unwrap().sign, Some(Signing::AdHoc));
        for bad in [&["--sign"][..], &["--sign", ""], &["--sign", "--open"], &["--frobnicate"], &["--sign", "x", "y"]] {
            assert!(parse_args(bad).is_err(), "{bad:?}");
        }

        let dev = Identity { keychain: PathBuf::from("/k/signing.keychain-db"), sha1: "D61A97A9F361BDE014B4AF6161AA2E8CFF0B6DF5".into() };
        // the flag wins, then the environment, then the local identity, else ad hoc
        assert_eq!(signing_for(Some(Signing::AdHoc), Some("X"), Some(dev.clone())), Signing::AdHoc);
        assert_eq!(signing_for(None, Some("X"), Some(dev.clone())), Signing::Named("X".into()));
        assert_eq!(signing_for(None, Some("-"), Some(dev.clone())), Signing::AdHoc);
        assert_eq!(signing_for(None, Some("  "), Some(dev.clone())), Signing::Dev(dev.clone()));
        assert_eq!(signing_for(None, None, Some(dev.clone())), Signing::Dev(dev));
        assert_eq!(signing_for(None, None, None), Signing::AdHoc);
    }

    #[test]
    fn short_version_drops_the_prerelease() {
        assert_eq!(short_version("0.4.0"), "0.4.0");
        assert_eq!(short_version("1.2.3-rc.1"), "1.2.3");
    }
}
