//! `cargo xtask bundle [--release|--debug] [--open] [--release-id]`: a local macOS `FilmCraft Dev.app`
//! (`FilmCraft.app` with the release bundle id under `--release-id`).
//!
//! Builds the `filmcraft` binary and assembles `<target>/<profile>/FilmCraft.app` with its own
//! Info.plist (camera / microphone usage descriptions, document types), the icon and an ad-hoc
//! signature, so macOS attributes the camera, microphone and Screen Recording permissions to
//! FilmCraft instead of the terminal that started it. It copies the binary and the icon only:
//! everything else is embedded. Release packaging (universal binary, Developer ID, notarisation,
//! DMG) is `packaging/macos/package.sh`. On other hosts it does nothing.

use std::path::{Path, PathBuf};
use std::process::Command;

/// The bundle identifier, the same as the release bundle (`packaging/macos/Info.plist.in`) and the
/// Linux app id (`packaging/linux/ai.storyteller.filmcraft.desktop`).
pub const BUNDLE_ID: &str = "ai.storyteller.filmcraft";
/// The local build's bundle id and name. A local bundle must not share the release id: Launch
/// Services resolves a bundle id to the registered copy, so `open` on a local `FilmCraft.app` can
/// start an installed release instead (it did, on the owner's Mac, with FilmCraft 0.2.1 in
/// /Applications).
pub const DEV_BUNDLE_ID: &str = "ai.storyteller.filmcraft.dev";
pub const DEV_NAME: &str = "FilmCraft Dev";

/// ScreenCaptureKit (linked by `crates/platform/src/capture/screen.rs`) needs macOS 12.3; its
/// macOS 13 API (`capturesAudio`) is checked at run time.
pub const MIN_MACOS: &str = "12.3";

pub const CAMERA_USAGE: &str = "FilmCraft records your camera when you press Record.";
pub const MICROPHONE_USAGE: &str = "FilmCraft records your microphone for voice-over and recordings.";

fn esc(s: &str) -> String {
    s.replace('&', "&amp;").replace('<', "&lt;").replace('>', "&gt;")
}

/// `CFBundleVersion` / `CFBundleShortVersionString` must be numeric: `0.4.0-rc.1` → `0.4.0`.
pub fn short_version(version: &str) -> &str {
    version.split_once('-').map_or(version, |(core, _)| core)
}

/// The bundle's Info.plist for the workspace `version`, bundle `id` and display `name`.
pub fn info_plist(version: &str, id: &str, name: &str) -> String {
    let short = esc(short_version(version));
    let full = esc(version);
    let id = esc(id);
    let name = esc(name);
    let camera = esc(CAMERA_USAGE);
    let mic = esc(MICROPHONE_USAGE);
    format!(
        r#"<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<!-- Generated by `cargo xtask bundle` (xtask/src/bundle.rs). -->
<plist version="1.0">
<dict>
  <key>CFBundleDevelopmentRegion</key>
  <string>en</string>
  <key>CFBundleIdentifier</key>
  <string>{id}</string>
  <key>CFBundleName</key>
  <string>{name}</string>
  <key>CFBundleDisplayName</key>
  <string>{name}</string>
  <key>CFBundleExecutable</key>
  <string>filmcraft</string>
  <key>CFBundleIconFile</key>
  <string>filmcraft</string>
  <key>CFBundleInfoDictionaryVersion</key>
  <string>6.0</string>
  <key>CFBundlePackageType</key>
  <string>APPL</string>
  <key>CFBundleSignature</key>
  <string>????</string>
  <key>CFBundleShortVersionString</key>
  <string>{short}</string>
  <key>CFBundleVersion</key>
  <string>{short}</string>
  <key>FilmCraftVersion</key>
  <string>{full}</string>
  <key>LSMinimumSystemVersion</key>
  <string>{MIN_MACOS}</string>
  <key>LSApplicationCategoryType</key>
  <string>public.app-category.video</string>
  <key>NSHighResolutionCapable</key>
  <true/>
  <key>NSSupportsAutomaticGraphicsSwitching</key>
  <true/>
  <key>NSHumanReadableCopyright</key>
  <string>Copyright © the FilmCraft authors. MIT OR Apache-2.0.</string>
  <key>NSCameraUsageDescription</key>
  <string>{camera}</string>
  <key>NSMicrophoneUsageDescription</key>
  <string>{mic}</string>
  <key>UTExportedTypeDeclarations</key>
  <array>
    <dict>
      <key>UTTypeIdentifier</key>
      <string>{id}.project</string>
      <key>UTTypeDescription</key>
      <string>FilmCraft Project</string>
      <key>UTTypeConformsTo</key>
      <array>
        <string>public.data</string>
        <string>public.json</string>
      </array>
      <key>UTTypeIconFile</key>
      <string>filmcraft</string>
      <key>UTTypeTagSpecification</key>
      <dict>
        <key>public.filename-extension</key>
        <array><string>fcproj</string></array>
        <key>public.mime-type</key>
        <array><string>application/x-filmcraft</string></array>
      </dict>
    </dict>
  </array>
  <key>CFBundleDocumentTypes</key>
  <array>
    <dict>
      <key>CFBundleTypeName</key>
      <string>FilmCraft Project</string>
      <key>CFBundleTypeRole</key>
      <string>Editor</string>
      <key>LSHandlerRank</key>
      <string>Owner</string>
      <key>CFBundleTypeIconFile</key>
      <string>filmcraft</string>
      <key>LSItemContentTypes</key>
      <array><string>{id}.project</string></array>
      <key>CFBundleTypeExtensions</key>
      <array><string>fcproj</string></array>
    </dict>
    <dict>
      <key>CFBundleTypeName</key>
      <string>Media</string>
      <key>CFBundleTypeRole</key>
      <string>Viewer</string>
      <key>LSHandlerRank</key>
      <string>Alternate</string>
      <key>LSItemContentTypes</key>
      <array>
        <string>public.movie</string>
        <string>public.audio</string>
        <string>public.image</string>
      </array>
    </dict>
  </array>
</dict>
</plist>
"#
    )
}

/// `CARGO_TARGET_DIR`, else `<root>/target`.
fn target_dir(root: &Path) -> PathBuf {
    match std::env::var_os("CARGO_TARGET_DIR").map(PathBuf::from) {
        Some(d) if d.is_absolute() => d,
        Some(d) => root.join(d),
        None => root.join("target"),
    }
}

fn dir_size(p: &Path) -> u64 {
    let Ok(md) = std::fs::symlink_metadata(p) else { return 0 };
    if !md.is_dir() {
        return md.len();
    }
    std::fs::read_dir(p).into_iter().flatten().flatten().map(|e| dir_size(&e.path())).sum()
}

fn run(cmd: &mut Command) -> Result<(), String> {
    eprintln!("$ {cmd:?}");
    let st = cmd.status().map_err(|e| format!("{cmd:?}: {e}"))?;
    if st.success() { Ok(()) } else { Err(format!("failed: {cmd:?}")) }
}

pub fn run_bundle(root: &Path, args: &[&str]) -> Result<(), String> {
    let mut release = true;
    let mut open = false;
    let mut release_id = false;
    for a in args {
        match *a {
            "--release" => release = true,
            "--debug" => release = false,
            "--open" => open = true,
            "--release-id" => release_id = true,
            _ => return Err(format!("bundle: unknown argument `{a}` (usage: cargo xtask bundle [--release|--debug] [--open] [--release-id])")),
        }
    }
    let (id, name) = if release_id { (BUNDLE_ID, "FilmCraft") } else { (DEV_BUNDLE_ID, DEV_NAME) };
    if !cfg!(target_os = "macos") {
        println!("bundle: a macOS app bundle; nothing to do on this host");
        return Ok(());
    }
    let manifest = root.join("Cargo.toml");
    let version = crate::version::read(&std::fs::read_to_string(&manifest).map_err(|e| format!("{}: {e}", manifest.display()))?)?;

    let mut build = Command::new(env!("CARGO"));
    build.current_dir(root).args(["build", "-p", "filmcraft", "--bin", "filmcraft"]);
    if release {
        build.arg("--release");
    }
    run(&mut build)?;

    let profile = if release { "release" } else { "debug" };
    let out = target_dir(root).join(profile);
    let bin = out.join("filmcraft");
    let app = out.join(format!("{name}.app"));
    if app.exists() {
        std::fs::remove_dir_all(&app).map_err(|e| format!("{}: {e}", app.display()))?;
    }
    let contents = app.join("Contents");
    let macos = contents.join("MacOS");
    let resources = contents.join("Resources");
    for d in [&macos, &resources] {
        std::fs::create_dir_all(d).map_err(|e| format!("{}: {e}", d.display()))?;
    }
    let copy = |from: &Path, to: &Path| std::fs::copy(from, to).map(|_| ()).map_err(|e| format!("copy {} → {}: {e}", from.display(), to.display()));
    copy(&bin, &macos.join("filmcraft"))?;
    copy(&root.join("assets/app-icon/filmcraft.icns"), &resources.join("filmcraft.icns"))?;
    let write = |p: PathBuf, data: &[u8]| std::fs::write(&p, data).map_err(|e| format!("{}: {e}", p.display()));
    write(contents.join("Info.plist"), info_plist(&version, id, name).as_bytes())?;
    write(contents.join("PkgInfo"), b"APPL????")?;

    run(Command::new("plutil").arg("-lint").arg(contents.join("Info.plist")))?;
    // Ad-hoc: one code identity for TCC, but a new one each build (permissions are asked again).
    run(Command::new("codesign").args(["--force", "--deep", "--sign", "-"]).arg(&app))?;
    run(Command::new("codesign").args(["--verify", "--strict"]).arg(&app))?;
    println!("bundle: {} ({name} {version}, {id}, {profile}, {:.1} MB)", app.display(), dir_size(&app) as f64 / 1e6);
    if open {
        run(Command::new("open").arg(&app))?;
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn value_of(plist: &str, key: &str) -> Option<String> {
        let tag = format!("<key>{key}</key>");
        let rest = &plist[plist.find(&tag)? + tag.len()..];
        let rest = rest.trim_start();
        if rest.starts_with("<true/>") {
            return Some("true".into());
        }
        let rest = rest.strip_prefix("<string>")?;
        Some(rest[..rest.find("</string>")?].to_string())
    }

    #[test]
    fn info_plist_has_the_keys_and_the_workspace_version() {
        let manifest = std::fs::read_to_string(Path::new(env!("CARGO_MANIFEST_DIR")).join("../Cargo.toml")).unwrap();
        let version = crate::version::read(&manifest).unwrap();
        let p = info_plist(&version, DEV_BUNDLE_ID, DEV_NAME);
        let short = short_version(&version).to_string();
        let r = info_plist(&version, BUNDLE_ID, "FilmCraft");
        assert_eq!(value_of(&r, "CFBundleIdentifier").as_deref(), Some(BUNDLE_ID));
        assert_eq!(value_of(&r, "CFBundleName").as_deref(), Some("FilmCraft"));
        assert!(r.contains(&format!("<string>{BUNDLE_ID}.project</string>")));
        assert_ne!(DEV_BUNDLE_ID, BUNDLE_ID, "a local bundle never takes the release id");
        for (k, v) in [
            ("CFBundleIdentifier", DEV_BUNDLE_ID),
            ("CFBundleName", DEV_NAME),
            ("CFBundleDisplayName", DEV_NAME),
            ("CFBundleExecutable", "filmcraft"),
            ("CFBundleIconFile", "filmcraft"),
            ("CFBundlePackageType", "APPL"),
            ("CFBundleVersion", short.as_str()),
            ("CFBundleShortVersionString", short.as_str()),
            ("FilmCraftVersion", version.as_str()),
            ("LSMinimumSystemVersion", MIN_MACOS),
            ("LSApplicationCategoryType", "public.app-category.video"),
            ("NSHighResolutionCapable", "true"),
            ("NSCameraUsageDescription", CAMERA_USAGE),
            ("NSMicrophoneUsageDescription", MICROPHONE_USAGE),
        ] {
            assert_eq!(value_of(&p, k).as_deref(), Some(v), "{k}");
        }
        for s in [
            "<key>CFBundleDocumentTypes</key>",
            "<string>fcproj</string>",
            "<string>Owner</string>",
            "<string>Editor</string>",
            "<string>public.movie</string>",
            "<string>public.audio</string>",
            "<string>public.image</string>",
            "<string>Alternate</string>",
        ] {
            assert!(p.contains(s), "missing {s}");
        }
        assert!(!p.contains("NSScreenCaptureUsageDescription") && !p.contains("NSAppleEventsUsageDescription"));
        assert_eq!(p.matches("<dict>").count(), p.matches("</dict>").count());
        assert_eq!(p.matches("<array>").count(), p.matches("</array>").count());
    }

    #[test]
    fn short_version_drops_the_prerelease() {
        assert_eq!(short_version("0.4.0"), "0.4.0");
        assert_eq!(short_version("1.2.3-rc.1"), "1.2.3");
    }
}
